
-- Database for Grocery Store Management
CREATE DATABASE Grocery_Store_Management;
USE Grocery_Store_Management;
-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


-- Analysis Questions
-- 1. Customer Insights
--     Gain an understanding of customer engagement and purchasing behavior.
--  1. How many unique customers have placed orders?
SELECT 
    COUNT(DISTINCT cust_id)
FROM
    orders; 

-- 2. Which customers have placed the highest number of orders?

SELECT 
    cust_id, COUNT(*) AS order_count
FROM
    orders
GROUP BY cust_id
ORDER BY order_count DESC
LIMIT 10;

-- 3. What is the total and average purchase value per customer?
select c.cust_id, c.cust_name,sum(od.total_price) as Total_purchase,avg(od.total_price) as Avg_Purchase from customers c
join orders as o on c.cust_id = o.cust_id
join order_details as od on o.ord_id = od.ord_id
join products as prod on od.prod_id = prod.prod_id
group by c.cust_id,c.cust_name order by cust_id asc;


--  4. Who are the top 5 customers by total purchase amount?
select c.cust_id as cust_id, c.cust_name as cust_name,sum(od.total_price) as Total_spend from customers as c
join orders as o on c.cust_id = o.cust_id
join order_details as od on o.ord_id = od.ord_id
group by cust_id,cust_name order by Total_spend desc limit 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- 5. How many products exist in each category?
select cato.cat_id as cat_id,cato.cat_name as cat_name,count(*) No_of_prod from categories as cato
join products as prod on prod.cat_id = cato.cat_id
group by cat_id;

-- 6. What is the average price of products by category?
select cato.cat_id as cat_id, cato.cat_name as cat_name,avg(od.each_price) as avg_category
from categories as cato
join products as prod on cato.cat_id = prod.cat_id
join order_details as od on prod.prod_id = od.prod_id
group by cat_id;

-- 7. Which products have the highest total sales volume (by quantity)?
select prod.prod_id as prod_id, prod.prod_name as prod_name, sum(quantity) as Total_quantity_sold
from products as prod
join order_details as od on prod.prod_id = od.prod_id
group by prod_id
order by Total_quantity_sold desc;

-- 8. What is the total revenue generated by each product?
select prod.prod_id as prod_id, prod.prod_name as prod_name,sum(od.total_price) as Revenue_for_product from products as prod
join order_details as od on prod.prod_id = od.prod_id
group by prod_id;

-- 9. How do product sales vary by category and supplier?
SELECT 
    c.cat_name AS Category,
    s.sup_name AS Supplier,
    SUM(od.quantity) AS Total_Quantity_Sold,
    SUM(od.total_price) AS Total_Sales_Amount
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories c ON p.cat_id = c.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_name, s.sup_name
ORDER BY Total_Sales_Amount DESC;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- 10. How many orders have been placed in total?
select count(ord_id) as total_orders from orders;

-- 11. What is the average value per order?
SELECT 
    AVG(order_total) AS avg_value_per_order
FROM (
    SELECT 
        od.ord_id,
        SUM(od.total_price) AS order_total
    FROM order_details AS od
    GROUP BY od.ord_id
) AS order_totals;


-- 12. On which dates were the most orders placed?
SELECT order_date, COUNT(*) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;


-- 13. What are the monthly trends in order volume and revenue?
SELECT 
    DATE_FORMAT(STR_TO_DATE(o.order_date, '%m/%d/%Y'), '%Y-%m') AS Month,
    COUNT(DISTINCT o.ord_id) AS TotalOrders,
    SUM(od.total_price) AS TotalRevenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY Month
ORDER BY Month;


-- 14. How do order patterns vary across weekdays and weekends?
SELECT 
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(o.order_date, '%m/%d/%Y')) IN (1, 7) 
            THEN 'Weekend'
        ELSE 'Weekday'
    END AS DayType,
    COUNT(distinct o.ord_id) AS TotalOrders,
    SUM(od.total_price) AS TotalRevenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY DayType;

-- 4. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- 15. How many suppliers are there in the database?
select count(*) as no_of_suppliers from supplier;

-- 16. Which supplier provides the most products?
select s.sup_id as sup_id,s.sup_name as sup_name, count(prod.prod_id) as no_of_products from products as prod
join supplier as s on s.sup_id = prod.sup_id
group by s.sup_id 
order by no_of_products desc limit 1; 

-- 17. What is the average price of products from each supplier?
select s.sup_name ,avg(prod.price) as avg_price from supplier s
join products prod on s.sup_id=prod.sup_id
group by s.sup_name;


-- 18. Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.sup_id,
    s.sup_name,
    SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

-- 5. Employee Performance
-- Assess how employees are handling and influencing sales.
-- 19. How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS employees_processed_orders
FROM orders;

-- 20. Which employees have handled the most orders?
SELECT 
    e.emp_id,
    e.emp_name,
    COUNT(o.ord_id) AS total_orders_handled
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders_handled DESC;


-- 21. What is the total sales value processed by each employee?
SELECT 
    e.emp_id,
    e.emp_name,
    SUM(od.total_price) AS total_sales_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;


-- 22. What is the average order value handled per employee?
SELECT 
    e.emp_id,
    e.emp_name,
    AVG(od.total_price) AS avg_order_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;


-- 6. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- 23. What is the relationship between quantity ordered and total price?
select pord_id,prod_name,quantity,each_price,(quantity * each_price) as total_price from order_details;

-- 24. What is the average quantity ordered per product?
select prod.prod_id,prod.prod_name,(avg(od.quantity)) as Avg_quantity from products as prod
join order_details as od on prod.prod_id = od.prod_id
group by prod.prod_id,
prod.prod_name;

-- 25. How does the unit price vary across products and orders?
SELECT 
    p.prod_id,
    p.prod_name,
    MIN(od.each_price) AS min_unit_price,
    MAX(od.each_price) AS max_unit_price,
    AVG(od.each_price) AS avg_unit_price,
    COUNT(DISTINCT od.ord_id) AS total_orders
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_unit_price DESC;

